# Generated by Django 5.0.6 on 2024-06-20 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Product')),
                ('description', models.TextField(max_length=500, verbose_name='Description')),
                ('slug', models.SlugField()),
                ('price', models.IntegerField()),
                ('stock', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('out of stock', 'Out of Stock'), ('in stock', 'In Stock')], default='in stock', max_length=100)),
                ('subcategories', models.ManyToManyField(to='category.subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
