# Generated by Django 5.0.6 on 2024-06-24 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_subcategories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='subcategories',
            new_name='category',
        ),
    ]
