# Generated by Django 5.0.6 on 2024-06-24 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_size_productsize_productsize_unique_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsize',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_size', to='product.product'),
        ),
    ]
