# Generated by Django 5.0.6 on 2024-06-24 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_remove_product_status_remove_product_stock'),
        ('user', '0006_remove_cart_product_cart_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product_size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productsize'),
        ),
    ]
