# Generated by Django 5.0.6 on 2024-07-11 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_cart_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='session_key',
        ),
    ]
